---
- hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - role: "otc_auth"
    - role: "otc_rds"
      rds_name: "{{ lookup('env','RDS_NAME') }}"
      localaction: "backups"

  tasks:
    - name: Create backups.json file
      copy:
        content: "{{ rdsbackups.json|to_json }}"
        dest: ./backups.json
        mode: 0644
        force: yes
